### ISSUE TITLE
updatepkg fails for fc25

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#2003] opened 2020-04-25 12:54 UTC
In the latest alpha,  updatepkg fails for fc25 (not the others) with the following message:

.....
%description
Libraries required for LabView interface
%clean
%files
%defattr(-,root,root)
/usr/local/mdsplus/lib64/*LV*
%exclude /usr/local/mdsplus/lib64/*.a
Building target platforms: x86_64-linux
Building for target x86_64-linux
Processing files: mdsplus-alpha-labview_bin-7.102-5.fc25.x86_64
error: File not found: /workspace/releasebld/buildroot/usr/local/mdsplus/lib64/*LV*
RPM build errors:
    File not found: /workspace/releasebld/buildroot/usr/local/mdsplus/lib64/*LV*
Traceback (most recent call last):
  File "/opt/mdsplus/deploy/platform/redhat/redhat_build_rpms.py", line 243, in <module>
    buildRpms()
  File "/opt/mdsplus/deploy/platform/redhat/redhat_build_rpms.py", line 171, in buildRpms
    raise Exception("Error building rpm for package mdsplus%(bname)s%(packagename)s%(arch_t)s" % info)
Exception: Error building rpm for package mdsplus-alpha-labview_bin.x86_64
8d59b51f3888f5461bdf7630e1716df2a69d1e1a3ee8bddb1f1bc5f65c492185
======================================================
Docker redhat_docker_build.sh returned failure
status when exiting from mdsplus/builder:fc25
======================================================
============================================
Failure: The build was unsuccessful!
============================================

**Comment by zack-vii** [comment] 2020-04-25 12:59
this is not a bug. in your pr you only updated the debian packaging files. fc25 checks the packaging for redhat. since you did not update them, it fails by design.

**Comment by GabrieleManduchi** [comment] 2020-04-25 13:08
The PR failed because pudatepkg failed before (I was not aware when I did the PR)
The problem is in updatepkg that fails with the error message listed above. What actions should I do? I only added a couple of devices

**Comment by zack-vii** [comment] 2020-04-25 13:25
hm thats strange then i will check it out. the error is refering to laviw. did you change any labview stuff

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by GabrieleManduchi** [comment] 2020-04-25 13:27
No, I did not touch it

**Comment by zack-vii** [comment] 2020-04-25 13:49
how did you updatepkg? i just ran it and well your debian updates are also strange. i committed the chage.
i used deploy/updatepkg.sh  just make sure youdont have dangeling files flying around. if so you need to do a git stash; git reset --hard ; maybe a form of git clean.
the script works though.

**Comment by GabrieleManduchi** [comment] 2020-04-25 15:31
Hmmm....I cloned MDSplus alpha from scratch, and I get the same error running deploy/updatepkg

**Comment by zack-vii** [comment] 2020-04-25 15:43
hm maybe something wrong with your docker. or outdated images. i will set up a jenkins job later to see if your setup is broken or mine special

**Comment by GabrieleManduchi** [comment] 2020-04-25 16:30
You may try cloning from scratch a fresh alpha. I did this and  I tested upatepkg without touching anything else. I don't think my docker has problems: updatepkg worked well until this last time.

**Comment by zack-vii** [comment] 2020-04-27 11:34
hm looks like on jenkins teh environment variables a screwing with the paths.. in particular teh WORKSPACE env.. could you check if oyu have strange env. can you try if it works when you limit you env to PATH

**Comment by zack-vii** [comment] 2020-04-28 13:27
fixed with #2005

**Closed as completed by zack-vii** 2020-04-28 13:27 UTC
Labels: bug
