### ISSUE TITLE
Problem retrieving signal data in python (descriptor.py).

### ISSUE THREAD

**Issue by amicitas** [MDSplus/mdsplus#1018] opened 2017-08-29 13:12 UTC
I am getting and error when attempting to retrieve data from a signal using python.

This problem was introduced in version [alpha_release-7-14-0](https://github.com/MDSplus/mdsplus/releases/tag/alpha_release-7-14-0) and does not exist in [alpha_release-7-13-1](https://github.com/MDSplus/mdsplus/releases/tag/alpha_release-7-13-1).

Minimal example code for W7-X:

```
import os
import MDSplus

os.environ['qsw_eval_path'] = 'mds-data-2.ipp-hgw.mpg.de::'
tree = MDSplus.Tree('qsw_eval', 160309010)

node = tree.getNode('\QSW_EVAL::TOP.XICS.REVISION.AR16.X_100MS3CM.R01:TI')
ti = node.data()
```

Error message when using `alpha_release-7-14-0` or later:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-13-cafa24025061> in <module>()
----> 1 node.data()

/home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus/tree.py in data(self)
   1265 
   1266     def data(self):
-> 1267         return self.record.data()
   1268 
   1269     rfa=nciProp("rfa","data offset in datafile")

/home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus/tree.py in data(self)
   1265 
   1266     def data(self):
-> 1267         return self.record.data()
   1268 
   1269     rfa=nciProp("rfa","data offset in datafile")

/home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus/tree.py in record(self)
   1259     def record(self):
   1260         "Data contents of node (settable)"
-> 1261         return self.getRecord()
   1262     @record.setter
   1263     def record(self,value):

/home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus/tree.py in getRecord(self, *altvalue)
   1642                                        xd.byref)
   1643         if (status & 1):
-> 1644             return xd._setCtx(self.ctx).value
   1645         elif len(altvalue)==1 and status == _exc.TreeNODATA.status:
   1646             return altvalue[0]

/home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus/descriptor.py in value(self)
    130     def value(self):
    131         if self.l_length and self.pointer:
--> 132             return Descriptor(self.pointer,self.__dict__)._setCtx(self.ctx).value
    133 
    134 class Descriptor_xd(Descriptor_xs):

/home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus/descriptor.py in value(self)
    110     def value(self):
    111         if self.dtype:
--> 112             return dtypeToClass[self.dtype].fromDescriptor(self)._setCtx(self.ctx)
    113 
    114 class Descriptor_d(Descriptor_s):

/home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus/compound.py in fromDescriptor(cls, d)
    196     @classmethod
    197     def fromDescriptor(cls,d):
--> 198         args = [_dsc.pointerToObject(d.dscptrs[i]) for i in _ver.xrange(d.ndesc)]
    199         ans=cls(*args)
    200         if d.length>0:

/home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus/compound.py in <listcomp>(.0)
    196     @classmethod
    197     def fromDescriptor(cls,d):
--> 198         args = [_dsc.pointerToObject(d.dscptrs[i]) for i in _ver.xrange(d.ndesc)]
    199         ans=cls(*args)
    200         if d.length>0:

/home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus/descriptor.py in pointerToObject(pointer)
     18 def pointerToObject(pointer):
     19     if not pointer: return None
---> 20     return Descriptor(pointer).value
     21 
     22 class Descriptor(object):

/home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus/descriptor.py in value(self)
    110     def value(self):
    111         if self.dtype:
--> 112             return dtypeToClass[self.dtype].fromDescriptor(self)._setCtx(self.ctx)
    113 
    114 class Descriptor_d(Descriptor_s):

/home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus/compound.py in fromDescriptor(cls, d)
    196     @classmethod
    197     def fromDescriptor(cls,d):
--> 198         args = [_dsc.pointerToObject(d.dscptrs[i]) for i in _ver.xrange(d.ndesc)]
    199         ans=cls(*args)
    200         if d.length>0:

/home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus/compound.py in <listcomp>(.0)
    196     @classmethod
    197     def fromDescriptor(cls,d):
--> 198         args = [_dsc.pointerToObject(d.dscptrs[i]) for i in _ver.xrange(d.ndesc)]
    199         ans=cls(*args)
    200         if d.length>0:

/home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus/descriptor.py in pointerToObject(pointer)
     18 def pointerToObject(pointer):
     19     if not pointer: return None
---> 20     return Descriptor(pointer).value
     21 
     22 class Descriptor(object):

/home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus/descriptor.py in value(self)
    110     def value(self):
    111         if self.dtype:
--> 112             return dtypeToClass[self.dtype].fromDescriptor(self)._setCtx(self.ctx)
    113 
    114 class Descriptor_d(Descriptor_s):

KeyError: 213

```

**Comment by amicitas** [comment] 2017-08-29 13:32
It appears that between these two releases descriptor.py was entirely rewritten, which likely introduced this issue.

**Comment by tfredian** [comment] 2017-08-29 13:46
It is important to update the MDSplus python module after an the main MDSplus installation is updated. I don't know how your /home/IPP-HGW/npablant/.pyenv/versions/3.6.1/lib/python3.6/site-packages/MDSplus module was installed in the first place. The recommended way to update the python module is to do one of the following:

1. cd /usr/local/mdsplus/mdsobjects/python; python setup.py install
2.  pip install [--upgrade] [--user] /usr/local/mdsplus/mdsobjects/python

This should create the module with version information included (i.e. /usr/lib/python2.7/site-packages/mdsplus_alpha-7.16.0-py2.7.egg) which will also indicate whether your python module is compatible with the installed MDSplus software.

**Comment by amicitas** [comment] 2017-08-29 13:54
I have indeed upgraded my python module along with the latest MDSplus installation.  To determine the release where this issue was introduced, I only reinstalled the python module, not the rest of the MDSplus installation.  With an installation of MDSplus alpha_release_7-16-1 and the matching python module (7.16.1) this problem still exists.   With the same MDSplus installation but a python installation taken from alpha-release_7-13-1 everything works as expected.

**Comment by amicitas** [comment] 2017-08-29 13:58
In my case I did the installation from the git sources using the following procedure:

```
cd ~/temp
git clone git@github.com:MDSplus/mdsplus.git
cd mdsplus/mdsobjects/python
python setup.py sdist
cd dist
pip install mdsplus-1.0.tar.gz
```


Doing this the version information is not kept after the pip installation, but otherwise is identical to your option 2.

**Comment by zack-vii** [comment] 2017-08-29 14:06
by reading your first mail. according to your error log the most likely cause is that the dtype 213 is not registered in "descriptor.dtypeToClass"

probably because it is not very common or may deprecated or I simply forgot about it.
If you know the corresponding python class you may want to try adding it under 213 in descriptor.py .
If this fixes it we will have it out in the new release in no time.

cheers

Timo




On 29-Aug-17 3:58 PM, amicitas wrote:

In my case I did the installation from the git sources using the following procedure:

'''
cd ~/temp
git clone git@github.com<mailto:git@github.com>:MDSplus/mdsplus.git
cd mdsplus/mdsobjects/python
python setup.py sdist
cd dist
pip install mdsplus-1.0.tar.gz
'''

Doing this the version information is not kept after the pip installation, but otherwise is identical to your option #2<https://github.com/MDSplus/mdsplus/issues/2>.

**Comment by amicitas** [comment] 2017-08-29 14:59
The data should have just been a Float32Array:

Here is how I wrote the data originally.
```
            value = MDSplus.Float32Array(value_data.T.copy())
            value.setError(node_sigma)
            value.setUnits(units)
            value_signal = MDSplus.Signal(value, None, node_time, node_reff)
            node_value.record = value_signal
```

**Comment by tfredian** [comment] 2017-08-29 15:02
The problem is a bug in the handling of the with_error descriptor used when an error value is assigned to a value. We are looking into this problem now.

**Comment by tfredian** [comment] 2017-08-29 15:07
For a quick workaround until a new release is issued you can try editing compound.py in your python mdsplus module directory and find a class WithError(Compound) statement. 4 lines below that statement there is a dtype_id=211 statement. Change the 211 to 213 and this should fix the problem. Let us know if that solves your problem and we'll fix this for the next release.

**Comment by amicitas** [comment] 2017-08-29 15:35
I'll try this out tomorrow morning and get back to you. (I left the lab and can't seem to access W7-X remotely for the moment.)

**Comment by amicitas** [comment] 2017-08-30 06:49
I have reinstalled the python module from commit [5295173](https://github.com/MDSplus/mdsplus/commit/5295173da8ffd89b834d5e93c00529bb2e59be3f).  This resolves the issue and I am able to retrieve data from the node in question.  

Thank you for such a prompt fix for this issue!!  I believe that this issue can now be closed.

**Comment by tfredian** [comment] 2017-08-30 14:18
This was fixed by https://github.com/MDSplus/mdsplus/pull/1019 which was merged into alpha and is now in the latest alpha release.

**Closed as completed by tfredian** 2017-08-30 14:18 UTC
