### ISSUE TITLE
LabVIEW on Windows

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1434] opened 2018-10-19 12:13 UTC
```
16:57:19 x86_64-w64-mingw32-g++ -o /workspace/releasebld/64/bin_x86_64/MDSobjectsLVShr.dll -Wno-deprecated -fPIC -g -O3 -fvisibility=hidden  -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-strict-aliasing -mno-ms-bitfields -DWIN32 -D_WIN32  -I/mdsplus-docker/jenkins2/workspace/windows/src/3rd-party-apis/labview/cintools  -g -O3 -shared  mdsdataobjectswrp.o mdseventobjectswrp.o mdsipobjectswrp.o mdstreeobjectswrp.o -L/workspace/releasebld/64/bin_x86_64/  -lMdsShr -lTreeShr -lTdiShr -lMdsIpShr -lMdsObjectsCppShr "/mdsplus-docker/jenkins2/workspace/windows/src/3rd-party-apis/labview/cintools/labview-x86_64.lib"  

16:57:19 Warning: corrupt .drectve at end of def file

16:57:19 ar -cr /workspace/releasebld/64/bin_x86_64/MDSobjectsLVShr.a mdsdataobjectswrp.o mdseventobjectswrp.o
```

We might be linking against incompatible MSVC libs.

**Comment by tfredian** [comment] 2018-10-25 14:05
Gabriele, do you know if anyone is using LabView on Windows with any recent releases of MDSplus? For some reason the links to the labview/cintools lib's are producing warnings. I don't know how long these warnings have been happening so it might have been occurring ever since we switched to using MinGW64 for building MDSplus for windows. I don't know if the resulting dll's work with LabView or not.

**Comment by tfredian** [comment] 2018-10-25 14:11
If the LabView dll's are currently unusable it may be possible to change the build of the MDSobjectsLVShr.dll's to use visual studio using the same approach as mdsobjects/cpp/visual-studio-build.bat

**Comment by GabrieleManduchi** [comment] 2018-10-25 14:18
I think there are several LabView users on Windows, and I never got complains about this.

I will check the latest distribution on a Windows PC with labVIEW and I will let you know.

**Comment by zack-vii** [comment] 2018-10-27 12:27
if you look at the console output of windows release builds the  mdsobjects/cpp/visual-studio-build.bat script shows a lot of warnings that should be resolved. On in particular could cause LabVIEW to fail.. maybe:
```
<something> needs to have dll-interface to be used by clients of class <something else>
```
[mayby this helps](https://www.codeproject.com/Articles/28969/HowTo-Export-C-classes-from-a-DLL#CppMatureApproach)

**Comment by tfredian** [comment] 2018-11-07 14:07
The labview build for windows uses .lib files provided by LabView (iin 3rd-party-apps submodule). We need to find out whether this warning can just be ignored. If the labview interface on windows is broken we could use Visual Studio (preferably not) or possibly replace all calls to LabView DLL's with dynamic library loads. The linux build uses the dynamic loading now so perhaps the windows build could just do the same and not link against the lib files at all.

**Comment by GabrieleManduchi** [comment] 2018-11-07 14:53
Just found a Windows PC with LabVIEW installed (2013).
Got and installed the latest alpha distribution
Followed the steps in the tutorial for copying the VIs (I did not remember anything....)
Ran the sample program in the distribution (open a tree, read and write a tree node)
Everything worked!!

**Comment by zack-vii** [comment] 2018-11-07 15:01
@GabrieleManduchi : 
any chance the issues in mdsobjects/cpp/visual-studio-build.bat can be fixed. I assume this is the stuff that allows windows compilers to inherit MDSplus. Could that be affected by the issues indicated by 
```
<something> needs to have dll-interface to be used by clients of class <something else>
```
?

**Comment by GabrieleManduchi** [comment] 2018-11-07 15:50
I need to repeat the test on the Windows PC, not sure I was running the latest MDSplus version.

**Comment by GabrieleManduchi** [comment] 2018-11-07 18:05
Ok, I tested on a new machine. LabVIEW links correctly to MDSplus in Windows and executes MDSplus calls.

I have discovered however another issue related to a specific VI (with the latest version, I don't' know when it appeared) and I will look into it, but I don't think it is related to this issue.

Tom, have you any idea on how removing the message reported by Timo?

**Comment by tfredian** [comment] 2018-11-07 18:43
Gabriele, there are two separate issues here. Timo was commenting on both compiler warnings and the link warning when building the labview interface. Most of the compiler warnings are coming during the VS compiles when building the MDSobjectsCppShr-VS.dll which are caused by slightly different type declarations when using Microsoft api's instead of the MingW64 calls. Here are a few of them:
```
Z:\home\twf\mdsplus-alpha\include\mdsplus/ConditionVar.hpp(112): warning C4267: 'argument': conversion from 'size_t' to 'DWORD', possible loss of data
Z:\home\twf\mdsplus-alpha\include\mdsobjects.h(179): warning C4275: non dll-interface class 'std::exception' used as base for dll-interface class 'MDSplus::MdsException'
Z:\Microsoft-Visual-Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime_exception.h(43): note: see declaration of 'std::exception'
Z:\home\twf\mdsplus-alpha\include\mdsobjects.h(179): note: see declaration of 'MDSplus::MdsException'
Z:\home\twf\mdsplus-alpha\include\mdsobjects.h(935): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
Z:\home\twf\mdsplus-alpha\include\mdsobjects.h(942): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
Z:\home\twf\mdsplus-alpha\include\mdsobjects.h(948): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
Z:\home\twf\mdsplus-alpha\include\mdsobjects.h(1439): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
Z:\home\twf\mdsplus-alpha\include\mdsobjects.h(1519): warning C4251: 'MDSplus::Compound::descs': class 'std::vector<MDSplus::Data *,std::allocator<_Ty>>' needs to have dll-interface to be used by clients of class 'MDSplus::Compound'
        with
        [
            _Ty=MDSplus::Data *
        ]
Z:\home\twf\mdsplus-alpha\include\mdsobjects.h(1519): note: see declaration of 'std::vector<MDSplus::Da
```
He is just suggesting that we should probably fix these like we did with the rest of the warnings in MDSplus compiles. It is likely that some of our declarations in the modules and the headers might need to determine if the VS compiler is compiling the code and, if so, use different declarations to avoid the warnings.

**Comment by GabrieleManduchi** [comment] 2018-11-08 08:03
Ok, I will look into it, probably some conditional compilation will be required.
Anyway, I confirm that the current alpha version works properly in LabVIEW

**Comment by GabrieleManduchi** [comment] 2019-11-12 11:50
Will I close this? I confirm again that LabVIEW interface is currently used without problems in Windows

**Comment by zack-vii** [comment] 2019-11-26 21:23
Compiler warnings still persist. release-7-92-0

**Closed as completed** 2021-08-18 22:45 UTC
Labels: refactor
