### ISSUE TITLE
[python] list returned from Tree.getNodeWild() is broken

### ISSUE THREAD

**Issue by amicitas** [MDSplus/mdsplus#949] opened 2017-06-15 16:42 UTC
There is a problem with the list returned from Tree.getNodeWild().  Using `len()` on the returned list results in:

    TypeError: Arrays of type DTYPE_L are unsupported. Error message was: 'float' object cannot be interpreted as an integer

This list is also not iterable, and any attempt to iterate produced the same error.  

Current testing with alpha-7.9.5 on Debian Linux using python 3.6.
As far as I can tell this problem does not exist in stable-7.1.14.

Example code on w7x:

    import MDSplus
    tree =  MDSplus.Tree('QSW_EVAL', 160309010)
    node_name = 'XICS:ANALYSIS:100MS_3CM:AR16:*:TI'
    node_list = tree.getNodeWild(node_name)
    num = len(node_list)

This will produce the error given above.

**Comment by zack-vii** [comment] 2017-06-16 10:59
hm I have problems reproducing this on 2.7 and 3.4 (I don't have 3.6 atm) and the result is:
node_list: [129] and len(node_list): 1
 without raising any Exception. So it might either be a python 3.6 problem or it has been fixed in the latest release The latter however is unlikely since we did not change anything python related to my knowledge. Could you run "MDSplus.\_\_version\_\_" to verify the version of the MDSplus python package.

**Comment by amicitas** [comment] 2017-06-16 13:01
Here is the version information:

    In [3]: MDSplus.__version__
    Out[3]: '7.9.5'

I did a little further testing and I found that there problem does not exist in Python 3.4.4, but does exist in python 3.6.1.

**Comment by amicitas** [comment] 2017-06-16 14:28
I have tried using the python source from the `alpha` branch of github.  Same issue on Python 3.6.1.

**Comment by amicitas** [comment] 2017-06-16 14:52
I found the problem in:

    _descriptor.py Line:466

Integer division (//) or explicit conversion to int is required:

    shape=[int(descr.arsize/descr.length) if descr.length != 0 else 0,] 

I'll to see if I can figure out how to make a merge request.

**Comment by amicitas** [comment] 2017-06-16 14:57
Pull request created: https://github.com/MDSplus/mdsplus/pull/951

**Closed as completed** 2017-06-16 19:44 UTC
