### ISSUE TITLE
Jscope can not parse the this .dat file

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2076] opened 2020-07-02 20:51 UTC
I have a .dat file, would like to try jScope on it.  It chokes reading it in.

Enclosed.
[pp1_scope.dat.gz](https://github.com/MDSplus/mdsplus/files/4866594/pp1_scope.dat.gz)

**Comment by zack-vii** [comment] 2020-08-13 23:10
possible duplicate of #1540

**Closed as completed** 2023-04-04 19:47 UTC
Labels: bug, tool/jScope
