### ISSUE TITLE
Error reporting when using function mdsvalue in Matlab which version——alpha 7.139-60

### ISSUE THREAD

**Issue by pvolande** [MDSplus/mdsplus#2668] opened 2024-01-02 06:25 UTC
**Affiliation**
Institute of plasma physics, Chinese Academy of Sciences

**Version(s) Affected**
alpha 7.139-60

**Platform**
windows 10

**Describe the bug**
In the latest α version, calling the mdsvalue function in Matlab cannot return the data of the required signal

**To Reproduce**
1. In MATLAB 2019b, use the mdsvalue function to read signal data:
>>data = mdsvalue('\DFSDEV2'); 
2. Matlab will report an error：as shown
3. When I back the version to Stable 7.132-0, it's work. (But this version of numpy in Pyhon is outdated.)
4. Maybe it's an issue with the Matlab version， I haven't used it on the latest version of Matlab yet.

**Expected behavior**
n/a

**Screenshots**
![image](https://github.com/MDSplus/mdsplus/assets/65816597/9c110198-ae10-44eb-a961-08b537d206cd)

**Additional context**
n/a

**Comment by mwinkel-dev** [comment] 2024-01-02 18:34
This bug is likely related to Issue #2660.   However, not marking this as a duplicate because the error messages of this bug are not identical to those for #2660.   Nonetheless, if the root cause is the same, then PR #2661 will likely fix this bug too.

**Comment by ModestMC** [comment] 2024-01-02 21:01
I wonder if the different messages are the Windows equivalent. @pvolande you may want to test [the gm branch](https://github.com/MDSplus/mdsplus/tree/gm-fix-apd) that fixes the bug.

**Comment by mwinkel-dev** [comment] 2024-01-22 17:44
Hi @pvolande,

I was unable to reproduce this error using Windows 10, MATLAB R2023b, and MDSplus alpha 7.139.60+ (commit hash `f339f5379`).  

It is odd that the first error message is as follows:
```
MDSplus.MdsException:  %TREE-W-NOT_OPEN,  Tree not currently open
```
That is different than the behavior seen with Issue #2660 on Linux.   Thus, you've likely encountered a different issue.

Regardless, please try the new `alpha 7.139.61` release.   Let us know if that fixes the problem.

**Comment by mwinkel-dev** [comment] 2024-01-22 19:02
Hi @pvolande,

CORRECTION:   I was able to reproduce the issue using the `thin-client` mdsip connection.  (Previous testing was done with `thick-client` and `distributed-client`.)

```
>> y = mdsvalue(<some_signal>)
Error using javaToMatlab
Java exception occurred:
MDSplus.MdsException: %TREE-W-NOT_OPEN, Tree not currently open

	at MDSplus.Data.execute(Native Method)

	at MDSplus.Data.executeWithContext(Data.java:181)

	at MDSplus.Data.getShape(Data.java:345)


Error in mdsToMatlab (line 13)
        result = javaToMatlab(mdsthing);

Error in mdsvalue (line 53)
result = mdsToMatlab(result);
```

**Comment by mwinkel-dev** [comment] 2024-01-22 19:48
Hi @pvolande,

I have confirmed that `alpha 7.139.61` fixes this MATLAB issue with "thin-client" on Windows 10.   And that also confirms that this is a duplicate of Issue #2660.

**Comment by pvolande** [comment] 2024-01-25 09:34
Hi, @mwinkel-dev @ModestMC. 

- I express my heartfelt gratitude for your generous assistance. I am truly grateful for your help .
- Well, I have to admit that I am not very professional in coding. Many days agos, I tried swapping out the MATLAB folder from MDSplus-7.132-0 with the same one from MDSplus-alpha-7.139-60, and it worked. I'm sorry I was too busy and forgot to reply.
- And alpha 7.139.61, this version of the installation package can currently only be installed through Docker on Windows. I have not yet used Docker on Windows, so it may take some time to master it.

Abstract：MDSplus-alpha-7.139-60 (with matlab folder of MDSplus-7.132-0), MATLAB 2022b.
![image](https://github.com/MDSplus/mdsplus/assets/65816597/cb4962b5-b1f0-432f-aa13-bd9afdbb296c)
![image](https://github.com/MDSplus/mdsplus/assets/65816597/adb3bb7b-b181-4a66-8949-0cfc4e4584c1)

**Comment by mwinkel-dev** [comment] 2024-01-25 15:25
Hi @pvolande,

You're welcome.   Glad to read that you were able to fix the API for MATLAB on your computer.

The issue with the `alpha 7.139.61` release is that we've been doing maintenance on the build server, and thus the Windows installer for MDSplus was built but not made available.

We are close to finishing the maintenance work on the build server.  In a week or so (maybe sooner), you will be able to retrieve the Windows installer from either the mdsplus.org web site or GitHub.

**Comment by mwinkel-dev** [comment] 2024-02-07 02:33
Hi @pvolande,

You can now find the Windows installer (i.e., the *.exe file) for the `alpha-7.139-62` release on the GitHub site.  This has the MATLAB fix that was introduced in `-61`.
[alpha-7.139-62](https://github.com/MDSplus/mdsplus/releases)

We are continuing the maintenance work on our build server.   Soon you will also be able to obtain the Windows installer from the mdsplus.org web site.

**Comment by mwinkel-dev** [comment] 2024-02-15 19:02
Hi @pvolande,

I gather that the MATLAB issue has now been fixed at your site, so am closing this issue.

**Closed as completed by mwinkel-dev** 2024-02-15 19:02 UTC
Labels: bug, duplicate, api/matlab, branch/alpha
